### ISSUE TITLE
Bugs & Improvement

### ISSUE THREAD

**Issue by frteles** [mattmcspirit/hybridworkshop#5]
Hi Matt, 

Thanks for this workshop! Really an awesome hands-on experience. 

I've a couple of suggestions from the experience I had: 

1. Although I was able to register HCI cluster, I got the following message: 

![image](https://user-images.githubusercontent.com/66477616/124484498-c3db3000-ddab-11eb-8598-535deccf3e51.png)

And from Azure Portal:

![image](https://user-images.githubusercontent.com/66477616/124484571-dce3e100-ddab-11eb-8cdd-69f7c97ca1f0.png)

I don't know if the nodes are using the latest HCI version, or if this is expected, but just double checking that with you. 

2. Scale AKS nodes:

![image](https://user-images.githubusercontent.com/66477616/124484679-f9801900-ddab-11eb-9924-f67c3c842702.png)

The command you describe isn't available anymore. It changed to the one I'm sharing above. 

Also, the message should say we're scaling to 2 linux worker nodes and 1 windows worker nodes, since no windows worker nodes were there before. 

3. Adding NAT rule

I wasn't able to create the NAT rule as described in the guide, because the name isn't right, as you can see below:

![image](https://user-images.githubusercontent.com/66477616/124484845-364c1000-ddac-11eb-8396-4cab174cca38.png)

Once I changed the name to HYBRIDNAT, it worked perfectly. 

Thank you,
Francisco Teles

**Comment by frteles** [comment]
Also, do you think it makes sense to add after step 3, other step or a small exercise to create VMs? 

Just for the users to get the experience on how to create VMs in the server cluster and eventually Arc enabled them.

**Comment by mattmcspirit** [comment]
Hey - thanks for this.

1. This is now fixed, I've added a note to reflect the misleading error
2. Fixed, thanks for catching this
3. Fixed - thanks!

Adding a VM creation step too, hope that helps!
