### ISSUE TITLE
Feedback/Improvements

### ISSUE THREAD

**Issue by frteles** [mattmcspirit/hybridworkshop#7]
Hey Matt!

Tried again your workshop and here goes a couple of feedback for the AKS part, which got updated from what I can see:

"In the Add a node pool blade, enter the following, then click Add
Node pool name: LinuxPool1"

However, this pool name isn't supported anymore:

![image](https://user-images.githubusercontent.com/66477616/134637203-8d2f895c-1ba7-4e7e-85cc-4aa14d53ad5b.png)

"Next, you'll scale your Kubernetes cluster to have 2 Linux worker nodes and 1 Windows worker node:"

![image](https://user-images.githubusercontent.com/66477616/134637256-577b2154-44e8-443a-8465-ac0d55b9825b.png)

As far as I understood in the documentation, the PS commands changed to:

![image](https://user-images.githubusercontent.com/66477616/134637362-8ba8cf62-b3b0-42b5-9375-a36eec355a50.png)

And, at the end when I tried to use kubectl:

![image](https://user-images.githubusercontent.com/66477616/134637454-93b72185-06e6-4cee-abd3-b0b6a4ebc40b.png)

So, I'm sure if kubectl it still installed by default, of if it was just a transient error. However, I was able to install it easily with choco!

**Comment by mattmcspirit** [comment]
Hey - thanks for catching all these! I've made some edits to reflect the changes in the August AKS-HCI release, and added a workaround for the kubectl issue.

Thanks! :)
